### ISSUE TITLE
Poseidon252 as default lib for sponge hashes/permutations/preimage & Merkle Oppening proofs

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/Poseidon252#7]
To accomplish this, we should close:

- [x] Refactor actual lib to work with plonk including the sponge hash #5 
- [x] Add merkle tree hashing logic for `Scalar` and `Variable` as a gadget. #9 
- [x] Implement the merkle-tree proof generator as a gadget to use in the rest of libs where we need to perform merkle openning proofs. #10
- [x] Implement needed Kelvin-related Traits #12
- [x] Implement `From<Branch> for `PoseidonBranch` #13
- [x] Create a wrapping type over Scalar to define the `Content` trait over it #14
- [x] Finnish up documentation of the library #3 
- [x] Refactor auto-doc uploads to gh-pages. #15

**Comment by CPerezz** [comment]
Closed via #19
